[package]
name = "nnsplit-python"
version = "0.3.3-post"
authors = ["Benjamin Minixhofer <bminixhofer@gmail.com>"]
edition = "2018"

[package.metadata.maturin]
requires-dist = ["torch>=1.4,<2"]

[lib]
name = "nnsplit"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.13"
numpy = "0.11.0"
pyo3 = "=0.11.1"

[dependencies.nnsplit]
path = "../../nnsplit"
default-features =  false
features = ["model-loader"]
